package com.dineswift.userservice.model.entites;

public enum BookingStatus {
    PENDING,
    CONFIRMED,
    ORDER_COMPLETED,
    TABLE_RESERVED,
    WAITING_LIST,
    NO_SHOW,
    CANCELLED_BY_CUSTOMER,
    CANCELLED_BY_RESTAURANT,
    ON_HOLD,
    ARRIVED,
    SEATED,
    ORDER_PLACED,
    ORDER_CREATED,
    DINING,
    PAYMENT_PENDING,
    UPFRONT_PAYMENT_PENDING,
    UPFRONT_PAYMENT_COMPLETED;

}
