package com.dineswift.restaurant_service.model;

public enum BookingStatus {
    PAYMENT_PENDING,
    CONFIRMED,
    UPFRONT_PAYMENT_PENDING,
    UPFRONT_PAYMENT_COMPLETED,
    ORDER_COMPLETED,
    TABLE_RESERVED,
    WAITING_LIST,
    NO_SHOW,
    CANCELLED_BY_CUSTOMER,
    CANCELLED_BY_RESTAURANT,
    ON_HOLD,
    ARRIVED,
    SEATED,
    ORDER_PLACED,
    DINING,

}
